#!/usr/bin/env bash
# Prepares sql.js so it can run from a file:// page.
#
# sql.js's dist/sql-wasm.js is already UMD and exposes a global `initSqlJs` when loaded
# from a classic <script> tag, so it needs no bundler. Bundling it actually FAILS, because
# esbuild statically resolves the require('fs') / require('path') calls that live in its
# dead Node branch.
#
# The single real obstacle is the .wasm file, which Emscripten fetches at init time — and
# fetch of a sibling file is blocked under a null origin. The fix is to inline the wasm as
# base64 and hand it to initSqlJs via its `wasmBinary` option, which skips the fetch path
# entirely.
#
# The outputs are NOT committed. Generating them needs `npm install` regardless, so the
# "runs by opening a file, no build step" property is already lost for this one check —
# and 850 KB of base64 in the repo would buy nothing. Probes P1, P2, P3, P5 and P6 still
# run with no build step at all; only P4's FTS5 check needs this.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=node_modules/sql.js/dist
if [ ! -f "$SRC/sql-wasm.js" ]; then
  echo "sql.js not installed. Run first:"
  echo "  cd $(pwd) && npm init -y && npm install sql.js@1.11.0"
  exit 1
fi

mkdir -p vendor
cp "$SRC/sql-wasm.js" vendor/sql-wasm.js

python3 - "$SRC/sql-wasm.wasm" vendor/sql-wasm-binary.js <<'PY'
import base64, sys
src, dst = sys.argv[1], sys.argv[2]
with open(src, 'rb') as f:
    b64 = base64.b64encode(f.read()).decode('ascii')
with open(dst, 'w') as f:
    f.write("// Generated by tools/build-vendor.sh — do not edit.\n")
    f.write("// The sql.js wasm module, inlined so no fetch is needed under a null origin.\n")
    f.write("window.SQL_WASM_BINARY = (function () {\n")
    f.write("  var b64 = '%s';\n" % b64)
    f.write("  var raw = atob(b64);\n")
    f.write("  var out = new Uint8Array(raw.length);\n")
    f.write("  for (var i = 0; i < raw.length; i++) { out[i] = raw.charCodeAt(i); }\n")
    f.write("  return out;\n")
    f.write("}());\n")
print(f"inlined {len(b64)} base64 chars of wasm")
PY

echo "Built vendor/sql-wasm.js ($(du -h vendor/sql-wasm.js | cut -f1))"
echo "Built vendor/sql-wasm-binary.js ($(du -h vendor/sql-wasm-binary.js | cut -f1))"
