// Produce a single classic script that runs from file://.
//
// Two measured facts make this necessary, both from Phase 0: ES module imports fail under a
// null origin, and so does fetch of a sibling file. Hence IIFE format, and the wasm inlined
// as base64 rather than fetched at init.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';

const WASM = 'node_modules/@sqlite.org/sqlite-wasm/dist/sqlite3.wasm';
const BUDGET = 2 * 1024 * 1024;   // spec §9.1: the dashboard bundle stays under 2 MB

mkdirSync('src/generated', { recursive: true });
const b64 = readFileSync(WASM).toString('base64');
writeFileSync('src/generated/wasm-binary.ts',
`// Generated by build.mjs — do not edit.
// The SQLite wasm module, inlined because fetch is unavailable under a null origin.
const SQLITE_WASM_BASE64 = '${b64}';

let cached: Uint8Array | null = null;

/** Decode once: this is ~844 KB and the decode is not free. */
export function sqliteWasmBinary(): Uint8Array {
  if (cached) { return cached; }
  const raw = atob(SQLITE_WASM_BASE64);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) { out[i] = raw.charCodeAt(i); }
  cached = out;
  return cached;
}
`);
console.log(`inlined ${(b64.length / 1024 / 1024).toFixed(2)} MB of base64 wasm`);

const common = {
  bundle: true,
  format: 'iife',
  target: ['chrome113', 'firefox147', 'safari26'],
  minify: !process.argv.includes('--no-minify'),
  sourcemap: false,
  metafile: true,
  logLevel: 'warning'
};

// Two entry points: the library surface the Console and the conformance suite consume, and
// the standalone page. They are built separately rather than as one file because START.html
// must work with no API surface exposed, while the conformance page needs exactly that
// surface and no UI.
const reader = await build({
  ...common,
  entryPoints: ['src/index.ts'],
  globalName: 'SwissBunkerReader',
  outfile: 'dist/reader.js'
});
const app = await build({ ...common, entryPoints: ['src/ui/app.ts'], outfile: 'dist/app.js' });
// The Console is a separate entry point: it talks to the daemon and never touches the wasm,
// so bundling it with the reader would make it carry 1.1 MB it has no use for.
const console_ = await build({
  ...common, entryPoints: ['src/console/console.ts'], outfile: 'dist/console.js'
});

copyFileSync('src/ui/styles.css', 'dist/styles.css');
copyFileSync('src/console/console.css', 'dist/console.css');
copyFileSync('src/console/console.html', 'dist/index.html');

for (const [label, result] of [['reader.js', reader], ['app.js', app], ['console.js', console_]]) {
  const bytes = Object.values(result.metafile.outputs)[0].bytes;
  console.log(`built dist/${label} — ${(bytes / 1024 / 1024).toFixed(2)} MB`);
  if (bytes > BUDGET) {
    console.warn(`WARNING: dist/${label} is ${((bytes - BUDGET) / 1024).toFixed(0)} KB over the 2 MB budget from spec §9.1`);
  }
}
// Both bundles inline the same 1.1 MB of wasm, so START.html would pay for it twice if it
// loaded both. It loads only app.js. Phase 5 collapses this when the Console arrives.
